### ISSUE TITLE
check 2019 SST map vs time series

### ISSUE THREAD

**Issue by bbest** [NOAA-EDAB/ecodata#28]
In [LTL > Gulf of Maine & Georges Bank > Ocean Temperature > SST](https://noaa-edab.github.io/ecodata/LTL#ocean_temperature10), there's an odd cold pool in the map of Georges Bank that doesn't seem to match with time series...

### map

![image](https://user-images.githubusercontent.com/2837257/72979701-e8ee0580-3da6-11ea-883b-20249377444c.png)

## timeseries

![image](https://user-images.githubusercontent.com/2837257/72979722-f5725e00-3da6-11ea-9ed4-5f64f460b382.png)

**Comment by bbest** [comment]
Hi @kimberly-bastille, here's the culprit:

- https://github.com/marinebon/ecodata/commit/f83638e4ecb612c47a742b1d072d6df5ff640c77#diff-c1941e29a573956026393e68914ec400R843

Swapping in out this one line with the original in the latest `LTL.Rmd`:

```r
#sst <- seasonal_sst_anomaly_gridded  # from:   f83638e
sst <- seasonal_oisst_anom_gridded    # before: f83638e
```

produces this map in contrast to above:

![image](https://user-images.githubusercontent.com/2837257/72980573-d7a5f880-3da8-11ea-9c03-d1cdcd71f5ab.png)

**Comment by bbest** [comment]
So @kimberly-bastille says these two are from different years:
- 2019: `sst <- seasonal_sst_anomaly_gridded           # from:   f83638e`
- 2018: `sst <- seasonal_oisst_anom_gridded             # before: f83638e`

## R code

We'll need to tease apart the various places SST gets calculated/generated in a consistent manner:

- [R/](https://github.com/NOAA-EDAB/ecodata/tree/master/R)
  * [long_term_sst.R](https://github.com/NOAA-EDAB/ecodata/blob/master/R/long_term_sst.R)
  * [seasonal_oisst_anom.R](https://github.com/NOAA-EDAB/ecodata/blob/master/R/seasonal_oisst_anom.R)
  * [seasonal_oisst_anom_gridded.R](https://github.com/NOAA-EDAB/ecodata/blob/master/R/seasonal_oisst_anom_gridded.R)
- [data-raw/](https://github.com/NOAA-EDAB/ecodata/tree/master/data-raw)
  * [get_long_term_sst.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_long_term_sst.R)
  * [get_oceantemp_insitu.R](https://github.com/NOAA-EDAB/ecodata/blob/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/data-raw/get_oceantemp_insitu.R)
  * [get_oisst.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_oisst.R)
  * [get_seasonal_oisst_anom.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_seasonal_oisst_anom.R)
  * [get_seasonal_oisst_anom_gridded.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_seasonal_oisst_anom_gridded.R)
- [docs/](https://github.com/NOAA-EDAB/ecodata/tree/master/docs)
  * [LTL.Rmd](https://github.com/marinebon/ecodata/blame/master/docs/LTL.Rmd#L843)
- [other/Rmd/](https://github.com/NOAA-EDAB/ecodata/tree/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/other/Rmd)
  * [process_env.Rmd](https://github.com/NOAA-EDAB/ecodata/blob/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/other/Rmd/process_env.Rmd)
  * [process_raw.Rmd](https://github.com/NOAA-EDAB/ecodata/blob/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/other/Rmd/process_raw.Rmd)


## Anomaly Calculation

There are at least 3 ways to calculate anomaly, given datasets at [ESRL : PSD : NOAA OI SST V2: High Resolution](https://www.esrl.noaa.gov/psd/data/gridded/data.noaa.oisst.v2.highres.html):

1. OLD: [Daily Mean](https://www.esrl.noaa.gov/psd/cgi-bin/db_search/DBListFiles.pl?did=132&tid=80486&vid=2423) - sst.day.mean.ltm.1971-2000.nc
1. NEW: [Daily Mean](https://www.esrl.noaa.gov/psd/cgi-bin/db_search/DBListFiles.pl?did=132&tid=80486&vid=2423) - sst.day.mean.ltm.1982-2010.nc
1. COMPARE: [Daily Anomaly](https://www.esrl.noaa.gov/psd/cgi-bin/db_search/DBListFiles.pl?did=132&tid=80486&vid=2421)

### Datasets

- long-term mean (ltm):
  * sst.day.mean.ltm.1971-2000.nc: ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.ltm.1971-2000.nc
  * sst.day.mean.ltm.1982-2010.nc: ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.ltm.1982-2010.nc
- daily:
  * [Daily Mean](https://www.esrl.noaa.gov/psd/cgi-bin/db_search/DBListFiles.pl?did=132&tid=80486&vid=2423)
  * [Daily Anomaly](https://www.esrl.noaa.gov/psd/cgi-bin/db_search/DBListFiles.pl?did=132&tid=80486&vid=2421)

**Comment by seanhardison1** [comment]
A couple of clarifications:

- [data-raw/](https://github.com/NOAA-EDAB/ecodata/tree/master/data-raw)
  * [get_long_term_sst.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_long_term_sst.R): A long-term time series of SST for the whole NES

  * [get_oceantemp_insitu.R](https://github.com/NOAA-EDAB/ecodata/blob/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/data-raw/get_oceantemp_insitu.R): In-situ SST time series. Was not included in 2018-2019 SOE as it ended in 2017.

  * [get_oisst.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_oisst.R) and [get_seasonal_oisst_anom.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_seasonal_oisst_anom.R) appear to be the same script. I think I added "seasonal" to the filename to clarify what it did and then never removed get_oisst.R. It can be dropped.

  * [get_seasonal_oisst_anom_gridded.R](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_seasonal_oisst_anom_gridded.R) gives the gridded anomaly rather than the time series.

For 2018-2019, we used the 1982-2010 LTM for anomaly calculations. The above scripts in data-raw/ were used to process final SOE indicators. 

The scripts in other/ were an earlier iteration that had I pulled from the ECSA work. My recommendation is to use/iterate on the scripts in data-raw/, and the others can be dropped to avoid confusion.
