### ISSUE TITLE
Missing data in Gulf Stream index?

### ISSUE THREAD

**Issue by seanhardison1** [NOAA-EDAB/ecodata#37]
Hello!

In the documentation for the GSI, it mentions that the time series should extend from the present to 1954, but the data begin in 1993. Did the source for the GSI change?

**Comment by kimberly-bastille** [comment]
Good Catch! Yes, the source methods changed between 2019 and 2020 SOEs. The change is outlined in the [tech doc](https://noaa-edab.github.io/tech-doc/gulf-stream-index.html).

**Comment by kimberly-bastille** [comment]
Here are the notes that Vince sent in with the data. 

Gulf Stream Index (2019 GOM/GB/MAB)
 
The Gulf Stream Index (GSI) presented here is based on the average standard deviation of monthly sea level anomalies between 52oW and 72oW (Perez-Hernandez and Joyce, 2014) from 1993 to 2018 such that positive anomalies are indicative of a more northerly path of the Gulf Stream (northern shift in Gulf Stream north wall).  Since 2010, the GSI has an increasing trend (r2 = 0.35 monthly, r2 = 0.69 annually) indicating a northern shift in the Gulf Stream.   In the year 2018 (1.508), the GSI was at its most northerly position recorded since the year 1995 (1.605).   In June of 2018, the Gulf Stream was at record northerly position relative to the entire 1993-2018 record.  

A longer time-series (~50 years) of the Gulf Stream position based on in situ data in the extension zone near the Grand Banks also shows a northward shift of more than 2.6o in latitude (Seidov et al. 2019).  A more northerly Gulf Stream position is associated with warmer ocean temperature on the Northeast US shelf (Zhang et al. 2007) and a higher proportion of Atlantic Temperate Slope Water in the Northeast Channel (Saba et al. 2016).

2014 paper:  https://journals.ametsoc.org/doi/citedby/10.1175/JPO-D-13-0136.1

Saba, V.S., Griffies, S.M., Anderson, W.G., Winton, M., Alexander, M.A., Delworth, T.L., Hare, J.A., Harrison, M.J., Rosati, A., Vecchi, G.A., Zhang, R. 2016. Enhanced warming of the Northwest Atlantic Ocean under climate change. Journal of Geophysical Research: Oceans, 121(1), 118-132.

**Comment by seanhardison1** [comment]
Awesome, thanks Kim!
