### ISSUE TITLE
Resolve x.shade.min not found error

### ISSUE THREAD

**Issue by BBeltz1** [NOAA-EDAB/ecodata#63]
ggplot2 code in any chunk script is throwing "Error: object 'x.shade.min' not found"

**Comment by andybeet** [comment]
Are you trying to run each chunk script as is? If so this is the expected behavior. These values are declared in the rmds prior to plotting. see this for an example https://github.com/NOAA-EDAB/ecodata/blob/3c47e67d3d547b2da79e7e104ff2d8024a094a13/docs/human_dimensions_NE.Rmd#L92

I think Sarah and Sean specify these in their SOE rmds also.

**Comment by BBeltz1** [comment]
That is exactly what I was doing. I created this issue to ask about it, but you beat me to it. Thanks Andy!
