### ISSUE TITLE
Seasonal bottom temperature anomalies

### ISSUE THREAD

**Issue by seanhardison1** [NOAA-EDAB/ecodata#68]
Hello!

I'm in the hunt for seasonal bottom temperature anomalies on the NES. It looks like there's a gridded data product in `ecodata`, but it appears to be missing values and a year index:

![image](https://github.com/NOAA-EDAB/ecodata/assets/31781107/b8298f5c-83e2-4828-8fd4-2568baac0d6a)

I am using version 0.1.0

Thanks

Sean

**Comment by andybeet** [comment]
@kimberly-bastille This data set looks like it is a single year, 2022 only. Can you confirm?

It looks like the processing of the data and the creation of the data set happens [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_bottom_temp_comp.R) using the `bt_temp_anomaly_season_2022_soe.nc` file.

I am wondering if meant to use the `bt_temp_times_series_anomaly_epu.csv` file or if there is another script/raw-data that you used instead

I am happy to fix/update

**Comment by kimberly-bastille** [comment]
@seanhardison1 @andybeet Yes this data is for 2022. 

This is the bottom temp dataset equivalent to `ecodata::seasonal_sst_anomaly_gridded` . So it includes the same columns (Longitude, Latitude, Season, Value) to make it easy (in theory) for users. It includes NAs because the it does not cover the full ocean area the way satellite SST can. The model uses just datasets from the shelf. Below is how we visualized the data for the 2023 SOE MAFMC. The code can be found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/docs/LTL_MAB.Rmd) - starting on line 296. 

Time series for the data going back to 1959 is included in `ecodata::bottom_temp_comp`. 

<img width="456" alt="bt_spatial" src="https://github.com/NOAA-EDAB/ecodata/assets/39955661/5506ac6f-8a2f-4921-b5c1-fbf911b28b98">

**Comment by kimberly-bastille** [comment]
@BBeltz1 We haven't included it in the past but adding a `Time` column that includes the year of the data would add clarity for users. This should be added to `ecodata::seasonal_bt_anomaly_gridded`, `ecodata::seasonal_sst_anomaly_gridded` , and `ecodata::ches_bay_sst`. There may be others but these are the spatial datasets I could think of off the top.

**Comment by seanhardison1** [comment]
Thanks everyone! My mistake, I missed the `bottom_temp_comp` data set, which does appear to be what I'm looking for. Closing this.
